// Fails if web/src/types/generated/*.ts is stale vs contracts/web/*.schema.json
// — i.e. someone edited a schema (or a generated file) and forgot to run
// `npm run gen:types` before committing. See web/scripts/gen-types.mjs and
// web/package.json.
import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";
import { describe, expect, it } from "vitest";

const WEB_ROOT = path.resolve(fileURLToPath(import.meta.url), "../../..");
const CONTRACTS_DIR = path.resolve(WEB_ROOT, "..", "contracts", "web");
const GENERATED_DIR = path.resolve(WEB_ROOT, "src", "types", "generated");

const BANNER =
  "// AUTO-GENERATED by web/scripts/gen-types.mjs from contracts/web/*.schema.json.\n" +
  "// Do not edit by hand; run `npm run gen:types` after changing a schema.\n\n";

function toPascalCase(name: string): string {
  return name
    .split(/[-_.]/)
    .filter(Boolean)
    .map((part) => part[0]!.toUpperCase() + part.slice(1))
    .join("");
}

describe("generated types vs contracts/web/*.schema.json", () => {
  const schemaFiles = readdirSync(CONTRACTS_DIR)
    .filter((name) => name.endsWith(".schema.json"))
    .sort();

  it("covers every schema file with a generated .ts file", () => {
    const generated = readdirSync(GENERATED_DIR).filter((name) => name.endsWith(".ts") && !name.endsWith(".test.ts"));
    const expected = schemaFiles.map((name) => name.replace(/\.schema\.json$/, ".ts")).sort();
    expect(generated.sort()).toEqual(expected);
  });

  for (const fileName of schemaFiles) {
    const baseName = fileName.replace(/\.schema\.json$/, "");
    it(`${baseName}.ts matches ${fileName} (run \`npm run gen:types\` if this fails)`, async () => {
      const schema = JSON.parse(readFileSync(path.join(CONTRACTS_DIR, fileName), "utf-8"));
      const typeName = toPascalCase(baseName) + "Payload";
      const expectedTs =
        BANNER +
        (await compile(schema, typeName, {
          bannerComment: "",
          additionalProperties: false,
          style: { singleQuote: false },
        }));
      const actualTs = readFileSync(path.join(GENERATED_DIR, `${baseName}.ts`), "utf-8");
      expect(actualTs).toBe(expectedTs);
    });
  }
});
