#!/usr/bin/env node
// Generates web/src/types/generated/*.ts from contracts/web/*.schema.json.
// Run with `npm run gen:types` (see web/package.json). A vitest test
// (src/types/generated.test.ts) fails if these files are stale vs the
// schemas, so CI catches a forgotten regeneration.
import { compile } from "json-schema-to-typescript";
import { readFile, writeFile, mkdir, readdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const WEB_ROOT = path.resolve(fileURLToPath(import.meta.url), "../..");
const CONTRACTS_DIR = path.resolve(WEB_ROOT, "..", "contracts", "web");
const OUT_DIR = path.resolve(WEB_ROOT, "src", "types", "generated");

const BANNER =
  "// AUTO-GENERATED by web/scripts/gen-types.mjs from contracts/web/*.schema.json.\n" +
  "// Do not edit by hand; run `npm run gen:types` after changing a schema.\n\n";

async function main() {
  await mkdir(OUT_DIR, { recursive: true });
  const entries = await readdir(CONTRACTS_DIR);
  const schemaFiles = entries.filter((name) => name.endsWith(".schema.json")).sort();

  for (const fileName of schemaFiles) {
    const schemaPath = path.join(CONTRACTS_DIR, fileName);
    const raw = await readFile(schemaPath, "utf-8");
    const schema = JSON.parse(raw);
    const baseName = fileName.replace(/\.schema\.json$/, "");
    const typeName = toPascalCase(baseName) + "Payload";
    const ts = await compile(schema, typeName, {
      bannerComment: "",
      additionalProperties: false,
      style: { singleQuote: false },
    });
    const outPath = path.join(OUT_DIR, `${baseName}.ts`);
    await writeFile(outPath, BANNER + ts, "utf-8");
    console.log(`gen:types -> ${path.relative(WEB_ROOT, outPath)}`);
  }
}

function toPascalCase(name) {
  return name
    .split(/[-_.]/)
    .filter(Boolean)
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join("");
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
